### ISSUE TITLE
API

### ISSUE THREAD

**Issue by darkerin** [dyte-in/docs#211] opened 2023-09-29 13:46 UTC
### Are you certain it's a bug?

- [X] Yes, it looks like a bug

### Are you sure this is not an issue in Docusaurus?

- [X] It is not a Docusaurus issue

### Is there an existing issue for this?

- [X] I have searched existing issues, it hasn't been reported yet

### Issue description

Hello, I would like to provide feedback on an issue with interface debugging in a document. When I try to modify the request content in the body, there are some alignment issues with the styles.

<img width="1093" alt="image" src="https://github.com/dyte-in/docs/assets/136887833/eb0a452a-c6a8-49a2-93bc-e903bfa01b6b">

**Comment by darkerin** [comment] 2023-09-29 13:48
Another issue is that when I try to copy the interface URL, an extra line break is added.
https://api.dyte.io/v2
/meetings/{meeting_id}

<img width="1038" alt="image" src="https://github.com/dyte-in/docs/assets/136887833/195b0fec-696e-4bec-a1d7-c97a809821bd">

**Comment by vaibhavshn** [comment] 2023-09-29 14:06
Thanks for reporting. Having a look.

**Comment by darkerin** [comment] 2023-09-30 08:04
Thank you for your reply, This may indeed be a browser compatibility issue, i found this problem in chrome version 117.0.5938.132 (official version) (arm64),  But in safari it works.

**Comment by vaibhavshn** [comment] 2023-10-02 15:19
Closing this as one issue cannot be reproduced and the other one about newline being added when copying is from a third party library called stoplight elements: https://stoplight.io/open-source/elements, it is caused because the same text is separated by multiple div elements.

**Closed by vaibhavshn** 2023-10-02 15:19 UTC
